### PR TITLE
Default health check grace period

### PR DESCRIPTION
**Pull request by itstehkman**
Make health_check_grace_period default to timeout, otherwise validate it by making sure it is not greater than timeout if manually specified.

### CODE REVIEW

**Comment by grahamjenson** [comment]
Relevant docs https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html

**Comment by grahamjenson** [comment]
This looks good, but I would simplify and put the code into the `SetDefaults` function on the service. I think we could even hard code it as

```
service.Autoscaling.HealthCheckGracePeriod = release.Timeout
```

Having a `HealthCheckGracePeriod` longer than a deploy timeout will not do anything, and having one shorter than it means that the instance might be terminated before starting up.

Putting the code in SetDefaults means the `HealthCheckGracePeriod` attribute will be stored on the Release object making it easier to debug.

**Comment by itstehkman** [comment]
You're right, that is simpler, will do that instead.

**Comment by heimdall-asguard** [comment]
Review Error for grahamjenson @ 2018-11-02 11:17:18 UTC
User cannot review their own commit

**Comment by heimdall-asguard** [comment]
Review Error for haosu @ 2018-11-02 11:22:28 UTC
User failed mfa authentication

**Comment by heimdall-asguard** [comment]
Review Error for ropiku @ 2018-11-02 11:35:51 UTC
User must have write permissions to review

**Pull request merged**
