### PR TITLE
[Refactor] Upload KMS encrypted userdata to S3, to limit userdata access

### PR DESCRIPTION
**Pull request by grahamjenson**
Also:

1. expanded the ability for the different paths an instance profile an have, to allow for default and per project and per config profiles. This should make it easier to use and develop with Odin.
2. deploy only with files now since userdata is no longer in the release
3. adding `odin` prefix to roles so that external services can directly reference roles assigned by odin.

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/odin&ref=a554dbf3da2bd220ff4bf83ca1942fed1963e5e5)

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/odin&ref=28674f153a99097069f4f37b067a6ad2931c7a81)

**Comment by grahamjenson** [comment]
@brad-larson

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
brad-larson | 1 | approved 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/odin&ref=28674f153a99097069f4f37b067a6ad2931c7a81)

**Pull request merged**
